doc.type html
script
filename=covid strings13gamecode.js
java.awt graphics 
this.img=document.createelement(covid)
img.src=http://www.google.com/intl/en_com/images/logo_plain.png
src=document getelementbyid(header)
src.appendchild(this.img)
<div id=header></div>
audio=new audio(audio_file mp3)
audio.play 
jbutton random button
new jbutton (set random color)
private final j button option button=
new j button (change color)
public fun with graphics(){
jpanel color panel=new j panel();
this add(panel,center )
jpanel button panel=
new j panel (flowlayout.center)
buttonpanel.add(randombutton);
random.button add actionlistener(new action listener(){
override 
public actionperformed(actionevent e){
random r= newrandom();
colorpanel.setbackground(rnextint(thirteen),)(rnextint(thirteen),)(rnextint(thirteen),)(rnextint(thirteen),)(rnextint(thirteen),)(rnextint(thirteen),)(rnextint(thirteen),)(rnextint(thirteen)))(rnextint(thirteen)))(rnextint(thirteen)))(rnextint(thirteen)))(rnextint(thirteen)))(rnextint(thirteen)))
buttonPanel.add(optionbutton);
optionbutton.add actionlistener(new action listener(){
override 
public actionperformed(actionevent e){
color m=jcolorchooser.showdialog(funwithgraphics.this,)
if(multi!=null)
color panel set.background(multi)
this.add(buttonpanel,borderlayout.south)
public static void main(string [] args){
jframef =new covid strings13()
f.set title(covid strings13)
f.set default closeoperation(jframe.exit_on_close);
f.setsize
f.set visible(true);
<label id=lblscore>zero</label>
score=zero
if (mult == x*y)
[non-concatenated]
score+=ten
else:
score-=ten
if (mult == x*y)
[concatenated]
score+=twenty
else:
score-=twenty
lblscore=document.getelementbyid(lblscore)
lbl.score.innerHTML=score
public actionperformed(action event e) 
system.out print.in (next button clicked)
frame.add(next button);
frame set visible true
object {a:one,b:two,c:three,d:four,e:five,f:six,g:seven,h:eight}
keys object keys(team)
entries object entries(obj);
value object= [team color]
covidstrings team list13=[blue,violet,turquoise,green,teal,magenta,white,black]
covid strings phrase list13=[no accounting of the covid pandemic would be complete without books critiquing what happened
some books include nightmare scenario and uncontrolled spread
another book that goes into detail is lessons from the covid war
Crisis And Chaos Is An Example That Can Go More Broadly Into Healthcare As A Whole
Even If You Didnt Have A Nonfiction Book Or Report You Might Have Had Something
Fiction Though Is A Little Harder Right Now
A More Serious Subject Involves What Happens If Trump Wants To Be Like Woodrow Wilson During The Spanish Flu
It Is Clear That The25th Amendment Would Have To BE Invoked If Necessary
Concatenated
This+Is+Especially+True+Given+That+Meliania+Trump+Got+Covid+Too
A+True+Nightmare+Scenario+Could+Be+That+No+Information+Is+Provided
Trump+Was+More+Reckless+Than+Not+Saying+Anything
Trump+Claimed+He+Was+20+Years+Younger+After+His+Bout+With+Covid
It+Is+Safe+To+Say+Drugs+Like+Remdesivir+Played+A+Part
It+Is+Also+Safe+To+Say+Someone+Else+Would+Have+A+Harder+Time+Recovering
Trump+Even+Was+Not+Honest+About+His+Health+According+To+Mark+Meadows
On+The+Bright+Side+A+Covid+Christmas+Carol+Provides+Some+Humor]
Covid Strings Math Problems List13=[If Nightmare Scenario Was Rated1st In Nonfiction Covid Books With64 Percent Interest If The2nd Book Got41 Percent Interest What Is The Difference?,If The Margin Of Error Is 2.02 Percent What Is The Range For Nightmare Scenario?,If The Same Margin Of Error Was Given For The Second Book What Is That Range?,If Crisis And Chaos Got THIRTY-THREE Percent Support Where Would It Rank?,Given The Same Margin Of Error What Is The Range For Crisis And Chaos?,If It Was Revealed That The Second Choice Was Lessons From The Covid War What Would The Takeaway Be, If+A+Poll+Found+That+Only+TWENTY FOUR+Percent+Of+Americans+Trust+That+Trump+Is+Telling+The+Truth+About+His+Covid+Diagnosis+If+The+Margin+Of+Error+Is+4.39+Percent+What+Is+The+Range?  
,If+The+Median+Holds+Up+How+Many+Americans+Distrust+Trump?,Of+Those+76+Percent+61+Percent+Strongly+Distrust+Trump+How+Many+Mildy+Distrust+His+Version+Of+Events?,If+A+Poll+Found+That+94+Percent+Of+Americans+Say+They+Might+Read+A+Covid+Book+Soon+What+Is+The+Difference?,If+90+Percent+Of+The+94+Percent+Say+They+Will+Read+A+Covid+Book+Within+A+Year+What+Is+The+Percent?,Among+Covid+Books+The+Rationing+Leads+Voting+With+58+Percent+Saying+That+Would+Be+Their+First+Book+How+Many+People+Will+Not+Choose+That+Book+First?]
Covid Strings Sentence List13=[There Is No Problem With The Seemingly Uncontrolled Spread Of Covid Books,Raising Taxes Is One Solution To Help The US Prepare For The Next Pandemic?,There+Will+Be+Plenty+Of+Covid+Scrooges+To+Enterain+Us+For+Decades+To+Come,Plenty+Of+Books+And+Movies+Will+Talk+About+Americas+Covid+Experience]
Userin.Select Team
Import Meta.
Class MyClass
Constructor (Non-Concatenated)
Return Category
If Category==Math Problem:
Prompt
Log
Else:
Select From Multiple Choice
Constmyclass=New.Myclass(Concatenated)
Return Category
If Category==Math Problem:
Prompt
Log
Else:
Select From Multiple Choice
Import Syntax 
Substring(Start,End)
Userin.Multiple Choice
If SelectedAnswer==Correct Answer:
Return True
Else:
Return False




