doc.type html
script
html
head
utf8
viewportcontent=width=device-width,initial-scale=one>
title covid strings13 first round bracket
filename=covid strings13 first round.js
first round=(highest overall seed ,second highest seed third highest seed first middle seed, second middle seed,  third lowest seed ,second lowest seed,lowest overall seed)
highest overall seed = 1 seed
second highest seed=2 seed
third highest seed=3 seed
firstmiddleseed=4seed
second middle seed = 5 seed
third lowest seed= 6 seed
second lowest seed = 7 seed
lowest overall seed = 8 seed
teams=[blue,violet,turquoise,green,teal,magenta,white,black]
create matchup(magenta versus turquoise)
create matchup(white versus violet)
create matchup(black versus blue)
create matchup(teal versus green)
bracket =getelementbyid(bracket);
document.createelement 
matchupdiv.classname=(matchup)
matchupdiv.innerHTML =[matchup]
rounddiv.appendchild(matchup)
for (i in covid strings first round)
round div=create element
round div class name=covid strings11 first round
bracket.appendchild(round div)
if (event.target.covid strings seed list.contains(matchup))
event.target.covid strings seed list.toggle
else:
addmatchup
java util.scanner
java.util
questions[]questions={
question1
question2
question3
question4
question5
question6
question7
question8
question9
question10
question11
question12
question13
question14
question15
question16
if selectedanswer==correct:
return true
else:
return false
if selectedanswer=incorrect
return false
else:
return true
advancingteam=slice(current teams)
declareWinner
result=declarewinner(team1 score, team2 score)
if turquoise score>=forty:
console.log(turquoise waves win)
else:
console.log(magenta magnetizers win)
if violet score>=forty:
console.log(violet relivers win)
else:
console.log(white transit angels win)
if blue score>forty:
console.log(blue curve crushers win)
else:
console.log(black night riders win)
if green score>forty:
console.log(green peacemakers win)
else:
console.log(teal terminators win)
return filename
